---
title: "Dev-Ops for Data Scientists"
subtitle: "<br>Wifi: Posit Conf 2024 <br>Password: conf2024"
format: 
  revealjs:
    width: 1600
    height: 920
    max-scale: 1
    min-scale: 1
    smaller: true
    transition: fade
    background-transition: fade
    theme: theme.scss
    code-line-numbers: false
    menu: true
    code-block-height: 640px
engine: knitr
---


# {background-image="assets/background/title-slide-light.svg" background-size="1700px" background-color="white"}

::: {.content-slide-thin}
Welcome to
:::

::: {.content-slide}
**My awesome<br/>talk**
:::

::: {.content-slide-thin}
August 13
:::

# {background-image="assets/background/title-slide-dark.svg" background-size="1700px" background-color="#3D6E74"}

[My awesome talk]{style="color:#fff;font-size:140px;"}
<br/>
[My even <br/> better subtitle]{style="color:#ddd;font-size:80px;"}

# {background-image="assets/background/title-slide.svg" background-size="1700px" background-color="#3D6E74"}

[My awesome <br/>talk]{style="color:#fff;font-size:140px;"}
<br/>
[My even <br/> better subtitle]{style="color:#ddd;font-size:80px;"}


## [Slide light]{style="color:#666;"} {background-image="assets/background/slide-light.svg" background-size="1700px" background-color="white"}

<br/>

:::{.columns}
::: {.column width="20%"}
:::

::: {.column width="80%"}
::: custom
- Item 1
- Item 2
- Item 3
:::
:::
:::

## {background-image="assets/background/boxed-light.svg" background-size="1700px" background-color="white"}

<br/>

:::{.custom2}
I'm in a box!

:::

## {background-image="assets/background/boxed-green.svg" background-size="1700px" background-color="#799857"}

:::{.dark-slide}
A green slide!
:::

## {background-image="assets/background/boxed-dark.svg" background-size="1700px" background-color="#3D6E74"}

:::{.dark-slide}
Not a green slide!
:::

## {background-image="assets/background/content-slide.svg" background-size="1710px" background-color="#2a7070"}

:::{.content-slide-title}
Section 1
:::

:::{.content-slide}
Title of <br/> this section
:::

## {background-image="assets/background/content-green-dark.svg" background-size="1710px" background-color="#3D6E74"}

:::{.columns}
:::{.column width="35%"}
[My smart points]{style="color:#fff;font-size:120px;"}
:::
:::{.column width="65%"}
:::{.dark-slide}
- Smart point No. 1
- Smart point No. 2
- Smart point No. 3
:::
:::
:::

## {background-image="assets/background/content-dark-green.svg" background-size="1710px" background-color="#799857"}

:::{.columns}
:::{.column width="35%"}
[My smartier points]{style="color:#fff;font-size:120px;"}
:::
:::{.column width="65%"}
:::{.dark-slide}
- Smart point No. 1
- Smart point No. 2
- Smart point No. 3
:::
:::
:::

## [Here's some code]{style="color:#666;"} {background-image="assets/background/slide-light.svg" background-size="1700px" background-color="white"}

:::{.sample-code}
```r
as_tibble(iris)
#> # A tibble: 150 × 5
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#> 1          5.1         3.5          1.4         0.2 setosa 
#> 2          4.9         3            1.4         0.2 setosa 
#> 3          4.7         3.2          1.3         0.2 setosa 
#> 4          4.6         3.1          1.5         0.2 setosa 
#> 5          5           3.6          1.4         0.2 setosa 
#> 6          5.4         3.9          1.7         0.4 setosa 
#> # ℹ 144 more rows
```
:::

## {background-image="assets/background/thank-you.svg" background-size="1700px" background-color="#2a7070"}
